set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(triple x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${triple}-gcc)
set(CMAKE_CXX_COMPILER ${triple}-g++)
set(CMAKE_RC_COMPILER ${triple}-windres)
set(CMAKE_ASM_COMPILER ${triple}-as)

SET(QT_MOC_EXECUTABLE @MINGW_INSTALL_PREFIX@/bin/moc)
SET(QT_RCC_EXECUTABLE @MINGW_INSTALL_PREFIX@/bin/rcc)
SET(QT_UIC_EXECUTABLE @MINGW_INSTALL_PREFIX@/bin/uic)

LIST(APPEND CMAKE_PROGRAM_PATH @CMAKE_INSTALL_PREFIX@/bin ...)
SET(CMAKE_FIND_ROOT_PATH @MINGW_INSTALL_PREFIX@)
SET(CMAKE_INSTALL_PREFIX @MINGW_INSTALL_PREFIX@)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
