name: test
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:    
      - name: Install Dependencies
        run: |
          apt-get -y update
          apt-get -y install \
            build-essential \
            yasm \
            nasm \
            git \
            cmake \
            gyp \
            checkinstall \
            bison \
            flex \
            gettext \
            mercurial \
            subversion \
            ninja-build \
            automake \
            pkgconf \
            libtool \
            libtool-bin \
            gcc-multilib \
            g++-multilib \
            libgmp-dev \
            libmpfr-dev \
            libmpc-dev \
            libgcrypt-dev \
            gperf \
            ragel \
            texinfo \
            autopoint \
            re2c \
            asciidoc \
            python3-pip \
            docbook2x \
            unzip \
            p7zip-full \
            curl \
            jq \
            wget
          pip3 install -U --break-system-packages setuptools rst2pdf mako jsonschema meson  
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
          
      - uses: actions/checkout@main
      - name: Setup Toolchain
        run: |
          curl -OL https://github.com/eko5624/toolchain-test/releases/download/toolchain/dgn-cross-gcc.7z
          7z x dgn-cross-gcc.7z
          rm dgn-cross-gcc.7z
      - name: Building gcc with mcf
        run: |
          chmod +x ./test.sh
          ./test.sh


      - name: Packaging toolchain
        run: |
          7z a test.7z target/*

      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./release-package.sh
          ./release-package.sh test.7z
